### ISSUE TITLE
NATS TLS authentication

### ISSUE THREAD

**Issue by arnarg** [maxpert/marmot#71]
Are you open for support for TLS authentication in NATS being added?

This will require a SIGHUP (or any way of triggering a reload) handler that can re-read the certificate and key from the provided path.

Also it seems to be impossible to specify a custom CA certificate for the connection.

This could look something like this in the config:

```toml
[nats]
urls=["nats://localhost:4222"]
ca_file="/tmp/nats/ca.crt"
cert_file="/tmp/nats/client.crt"
key_file="/tmp/nats/client.key"
```
