### ISSUE TITLE
Crash: "double free or corruption (!prev)"

### ISSUE THREAD

**Issue by antiops** [maxpert/marmot#78]
I've been getting consistent crashes on the master server (in a master node + 1 replica setup). Both are on the latest version from the realeases page. Uptime is inconsistent. Sometimes its up for a day then crashes and sometimes it crashes within a few hours.

They're using basic configs so I might be missing an important thing that I do not know about.

The replica server has been running fine with no crashes.

## Configs:

> Master (`config-main.toml`)
```toml
db_path="/home/tik/redis/videos-replica.v2.db"
seq_map_path="/tmp/videos-main.cbor"

node_id=1

publish=true
replicate=false
```

> Replica (`config-replica.toml`)
```toml
db_path="/home/rep/tik/videos.v2.db"
seq_map_path="/tmp/videos-replica-1.cbor"

node_id=2

publish=false
replicate=true
```

## Details

Each instance is ran through the command line like
```
# Master
./marmot -config config-main.toml -cluster-addr 10.1.0.12:4223 -cluster-peers 'nats://10.1.0.1:14222/'

# Replica
./marmot -config config-replica.toml -cluster-addr 10.1.0.1:14222 -cluster-peers 'nats://10.1.0.12:4223/'
```

The database that it's using is 1.8GB with 4 tables of which only 1 (`videos_clean`) is being updated frequently. The master database is a replica itself to keep it separate from the production one, a script pushes changes to it every minute.

Below is the output from the most recent crash.

[marmot-v0.8.5-master-crashlog.txt](https://github.com/maxpert/marmot/files/12406561/marmot-v0.8.5-master-crashlog.txt)
